Traceback (most recent call last):
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/rucskajj/pkgs/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
discday = df['DISCOVERY_DOY'].replace('', np.nan).dropna().astype('int64')
discday_lf = df_lrg['DISCOVERY_DOY'].replace('', np.nan).dropna().astype('int64')

days_in_months = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] # Setting Feb = 29 days
month_bins = np.concatenate([[0],np.cumsum(days_in_months)])
month_ticks = (0.5*(month_bins[1::]-month_bins[0:-1:])+month_bins[0:-1:])
week_bins = np.arange(0,372,7)
week_bins[-1] = 366

fig, ax = plt.subplots(figsize=[5,3.5])

norm = 28 # to get bin values in number of fires per year
hist, bin_edges = np.histogram(discday, bins=week_bins)
ax.stairs(hist/norm, bin_edges, lw=2, color='C0')
ax.set_ylabel("Count per year (all fires)", fontsize=12, color='C0')

ax2=ax.twinx()
hist, bin_edges = np.histogram(discday_lf, bins=week_bins)
ax2.stairs(hist/norm, bin_edges, lw=2, color='C3')
ax2.set_ylabel("Count per year (large fires)", fontsize=12, color='C3')

for mb in month_bins[1:-1]:
    ax2.vlines(mb, 0, 100, color='k', ls='-', alpha=0.2, zorder=1)
ax2.set_ylim([0,100])

ax.set_xlim(0,366)
ax.set_xticks(days_ticks)
ax.set_xticklabels(["Jan.","Feb.","Mar.","Apr.","May","Jun","Jul.","Aug.","Sep.","Oct.","Nov.","Dec."])
ax.set_xlabel('Time of year', fontsize=12)
ax.set_title('Distribution of number of fires over time of year')

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_217/1833137881.py[0m in [0;36m<module>[0;34m[0m
[1;32m     25[0m [0;34m[0m[0m
[1;32m     26[0m [0max[0m[0;34m.[0m[0mset_xlim[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m366[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 27[0;31m [0max[0m[0;34m.[0m[0mset_xticks[0m[0;34m([0m[0mdays_ticks[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     28[0m [0max[0m[0;34m.[0m[0mset_xticklabels[0m[0;34m([0m[0;34m[[0m[0;34m"Jan."[0m[0;34m,[0m[0;34m"Feb."[0m[0;34m,[0m[0;34m"Mar."[0m[0;34m,[0m[0;34m"Apr."[0m[0;34m,[0m[0;34m"May"[0m[0;34m,[0m[0;34m"Jun"[0m[0;34m,[0m[0;34m"Jul."[0m[0;34m,[0m[0;34m"Aug."[0m[0;34m,[0m[0;34m"Sep."[0m[0;34m,[0m[0;34m"Oct."[0m[0;34m,[0m[0;34m"Nov."[0m[0;34m,[0m[0;34m"Dec."[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     29[0m [0max[0m[0;34m.[0m[0mset_xlabel[0m[0;34m([0m[0;34m'Time of year'[0m[0;34m,[0m [0mfontsize[0m[0;34m=[0m[0;36m12[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'days_ticks' is not defined
NameError: name 'days_ticks' is not defined

